import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:clientflutter/Models/User.dart';
import 'package:clientflutter/Screens/userApplication.dart';
import 'package:clientflutter/Screens/userContract.dart';
import 'package:clientflutter/Screens/clientPage.dart';
import 'dart:convert';
import 'dart:io';
import 'insuranceHome.dart';